version: "3.8"
services:
  tickets:
    build: .\
    ports:
      - "7000:8080"
      - "5005:5005"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USERNAME=postgres
      - POSTGRES_URL=jdbc:postgresql://flights:5432/flights
      - JAVA_TOOL_OPTIONS="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
    depends_on:
      - flights-db
  flights-db:
    image: postgres
    expose:
      - 5432
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=flights
    restart: always
    volumes:
      - flights:/var/lib/postgresql/data
volumes:
  flights: