server:
  port: 8080
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    username: postgres
    password: root
    url: jdbc:postgresql://flights:5432/flights
    driver-class-name: org.postgresql.Driver